-- users : id , name , email
drop table if exists hits;
create table if not exists hits
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar not null,
    uri varchar not null,
    ip varchar not null,
    created timestamp default now()
);

create index if not exists hits_idx
    on hits (app, uri, ip, created);

comment on table hits is 'Вещи пользователей';
comment on column hits.id is 'Идентификатор записи';
comment on column hits.app is 'Идентификатор сервиса для которого записывается информация';
comment on column hits.uri is 'URI для которого был осуществлен запрос';
comment on column hits.ip is 'IP-адрес пользователя, осуществившего запрос';
comment on column hits.created is 'Дата и время, когда был совершен запрос к эндпоинту (в формате "yyyy-MM-dd HH:mm:ss")';
