version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
